name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature-*'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Simulated Unit Tests
        run: echo "✅ Running tests... (simulated)"

      - name: Run Code Quality Checks
        run: echo "✅ Checking code quality... (simulated)"

  deploy-to-staging:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: echo "🚀 Deployed to staging environment (simulated)"
