name: Integration Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Placeholder Integration Test
      run: echo "No tests yet, placeholder passing test" && exit 0
